### ISSUE TITLE
Fatecoins?

### ISSUE THREAD

**Issue by CleiberReis** [WallaceRamos/SwapUp#1]
Olá guys!  :smile: 

O projeto está firme no fatecoins? Me avisem se estiver para eu investir em vocês! :+1: 

:rocket: - Go go SwapUp!

**Comment by WallaceRamos** [comment]
Ola Cleiber Rodrigues Reis

Tudo bem?

Não estamos mais trabalhando no projeto SwapUp pela dificuldade de
monetização, estamos na etapa de validaçao de um novo projeto, logo apos a
confirmação da validação vamos postalo no Fatecoins.

Agradeço pelo interesse em investir no nosso projeto.

Em qui, 17 de set de 2020 17:18, Cleiber Rodrigues Reis <
notifications@github.com> escreveu:

**Comment by CleiberReis** [comment]
Entendi! 

Espero que consigam validar a idéia e trazer esse projeto para a conclusão no sexto!
Se precisarem de ajuda, contem comigo ai!

Abraço!
